version: "3.7"
services:
  # app:
  #   image: node:12-alpine
  #   command: sh -c "yarn install && yarn dev"
  #   ports:
  #     - 3000:3000
  #   working_dir: /app
  #   volumes:
  #     - ./:/app
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: secret
  #     MYSQL_DB: todos

  gamearena-api:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: gamearena-mysql
      MYSQL_USERNAME: gamearena
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: coreapp
    depends_on:
      - gamearena-mysql
    # links:
    #   - gamearena-mysql:

  gamearena-mysql:
    image: mysql/mysql-server:8.0
    volumes:
      - "mysql-data:/var/lib/mysql"
      - "./backend/src/test/resources/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./backend/src/test/resources/data.sql:/docker-entrypoint-initdb.d/2.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: coreapp
      MYSQL_USER: gamearena
      MYSQL_PASSWORD: secret

volumes:
  mysql-data: